server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/post_microservice_db
    username: root
    password: 2002
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Enable JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

comment:
  service:
    url: http://localhost:8081/api/v1/comment